spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1016zsh..
    url: jdbc:mysql://localhost:3307/test
  #Redis配置
  redis:
    #IP地址
    host: localhost
    #端口
    port: 6379
    #数据库索引
    database: 15
    #密码
    password:
    #超时连接时间
    connect-timeout: 10s
    lettuce:
      pool:
        #连接池中的最小空闲连接
        min-idle: 0
        #连接池的最大空闲连接
        max-idle: 8
        #连接池的最大连接数
        max-active: 8
        #连接池的最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms